on:
  workflow_dispatch: ~
  push:
    branches: ['main', '*.*.x']
  pull_request: ~

jobs:
  check:
    uses: thesis-php/.github/.github/workflows/check.yml@main
    secrets: inherit
    with:
      psalm: true
      rector: true
      test: false
